app = "sunlight-rome"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false

[http_service.http_options]
h2_backend = true

[http_service.concurrency]
type = "requests"
hard_limit = 1000

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[mounts]]
source = "sunlight_rome"
destination = "/var/db/sunlight"
initial_size = "5GB"
auto_extend_size_threshold = 95
auto_extend_size_increment = "5GB"

[[metrics]]
port = 8080
path = "/metrics"

[[metrics]]
port = 9090
path = "/metrics"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 4

[[files]]
guest_path = "/etc/sunlight/rome2024h1.pem"
secret_name = "ROME2024H1_KEY"

[[files]]
guest_path = "/etc/sunlight/rome2024h2.pem"
secret_name = "ROME2024H2_KEY"

[[files]]
guest_path = "/etc/sunlight/rome2025h1.pem"
secret_name = "ROME2025H1_KEY"
